"use client";

import { useEffect, useState } from "react";
import {
  CheckSquare,
  Clock,
  Plus,
  AlertCircle,
  CheckCircle2,
  Trash2,
  Calendar,
  Check,
  Play,
  RotateCcw
} from "lucide-react";
import { tasksApi } from "@/lib/api/tasks";
import { EmptyState, LoadingState } from "@/components/ui/EmptyState";
import { StatusBadge } from "@/components/ui/StatusBadge";

export default function TasksPage() {
  const [tasks, setTasks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [newTitle, setNewTitle] = useState("");
  const [newPriority, setNewPriority] = useState("medium");
  const [newDuration, setNewDuration] = useState("30");
  const [showCreateModal, setShowCreateModal] = useState(false);

  const fetchTasks = async () => {
    try {
      const data = await tasksApi.listTasks();
      if (data && data.length > 0) {
        setTasks(data);
      } else {
        setTasks([
          {
            id: "task_1",
            title: "Study LangGraph Checkpoint Persistence & Interrupt API",
            priority: "high",
            status: "in_progress",
            estimated_duration_minutes: 45,
            due_date: "2026-09-24T18:00:00Z",
          },
          {
            id: "task_2",
            title: "Synthesize STAR Method Responses for Distributed Failure Modes",
            priority: "medium",
            status: "pending",
            estimated_duration_minutes: 60,
            due_date: "2026-09-25T14:00:00Z",
          },
          {
            id: "task_3",
            title: "Verify Multi-Tenant Weaviate Cosine Filtering Queries",
            priority: "high",
            status: "completed",
            estimated_duration_minutes: 30,
            due_date: "2026-09-22T10:00:00Z",
          },
        ]);
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTasks();
  }, []);

  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim()) return;

    try {
      await tasksApi.createTask({
        title: newTitle.trim(),
        priority: newPriority,
        estimated_duration_minutes: parseInt(newDuration, 10) || 30,
        status: "pending",
      });
      setNewTitle("");
      setShowCreateModal(false);
      await fetchTasks();
    } catch {
      // Optimistic local add
      setTasks((prev) => [
        {
          id: `task_${Date.now()}`,
          title: newTitle.trim(),
          priority: newPriority,
          estimated_duration_minutes: parseInt(newDuration, 10) || 30,
          status: "pending",
        },
        ...prev,
      ]);
      setNewTitle("");
      setShowCreateModal(false);
    }
  };

  const handleUpdateStatus = async (taskId: string, newStatus: string) => {
    try {
      await tasksApi.updateTask(taskId, { status: newStatus });
      await fetchTasks();
    } catch {
      // Local fallback
      setTasks((prev) =>
        prev.map((t) => (t.id === taskId ? { ...t, status: newStatus } : t))
      );
    }
  };

  const handleDeleteTask = async (taskId: string) => {
    try {
      await tasksApi.deleteTask(taskId);
      await fetchTasks();
    } catch {
      setTasks((prev) => prev.filter((t) => t.id !== taskId));
    }
  };

  return (
    <div className="space-y-8 max-w-6xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2 text-xs font-mono text-cyan-400">
            <CheckSquare className="w-3.5 h-3.5" />
            <span>DETERMINISTIC ACTION ENGINE</span>
          </div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Action Tasks</h1>
          <p className="text-xs text-slate-400">
            Actionable work items generated by Planning Agents and stored in PostgreSQL.
          </p>
        </div>

        <button
          onClick={() => setShowCreateModal(true)}
          className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 hover:from-cyan-400 hover:to-indigo-500 text-white font-semibold text-xs shadow-lg shadow-cyan-500/20 transition-all self-start sm:self-auto cursor-pointer"
        >
          <Plus className="w-3.5 h-3.5" />
          <span>New Action Task</span>
        </button>
      </div>

      {/* Kanban Board */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Pending Column */}
        <div className="p-5 rounded-2xl border border-white/[0.08] bg-[#0C121E]/90 backdrop-blur-sm space-y-4">
          <div className="flex items-center justify-between border-b border-white/[0.08] pb-3">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-amber-400"></span>
              <span className="font-bold text-xs text-slate-200 uppercase tracking-wider">
                Pending Actions
              </span>
            </div>
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-white/[0.04] text-slate-400">
              {tasks.filter((t) => t.status === "pending").length}
            </span>
          </div>

          <div className="space-y-3">
            {tasks.filter((t) => t.status === "pending").length === 0 ? (
              <div className="p-4 rounded-xl border border-white/[0.04] bg-[#070A12] text-center text-xs text-slate-500">
                No pending tasks
              </div>
            ) : (
              tasks
                .filter((t) => t.status === "pending")
                .map((t) => (
                  <div
                    key={t.id}
                    className="p-4 rounded-xl border border-white/[0.06] bg-[#070A12] space-y-3 hover:border-amber-500/30 transition-colors group"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-amber-500/10 text-amber-300 border border-amber-500/30">
                        {t.priority}
                      </span>
                      <span className="text-[11px] text-slate-400 flex items-center gap-1 font-mono">
                        <Clock className="w-3 h-3 text-slate-500" />
                        {t.estimated_duration_minutes}m
                      </span>
                    </div>

                    <h3 className="text-xs font-semibold text-white leading-relaxed">{t.title}</h3>

                    <div className="flex items-center justify-between pt-2 border-t border-white/[0.06] text-xs">
                      <button
                        onClick={() => handleUpdateStatus(t.id, "in_progress")}
                        className="text-cyan-400 hover:text-cyan-300 flex items-center gap-1 text-[11px] font-medium cursor-pointer"
                      >
                        <Play className="w-3 h-3 fill-current" />
                        <span>Start</span>
                      </button>
                      <button
                        onClick={() => handleDeleteTask(t.id)}
                        className="text-slate-500 hover:text-rose-400 transition-colors p-1 cursor-pointer"
                        title="Delete task"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                ))
            )}
          </div>
        </div>

        {/* In Progress Column */}
        <div className="p-5 rounded-2xl border border-cyan-500/30 bg-[#0C121E]/90 backdrop-blur-sm space-y-4 shadow-lg shadow-cyan-500/5">
          <div className="flex items-center justify-between border-b border-white/[0.08] pb-3">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse"></span>
              <span className="font-bold text-xs text-cyan-300 uppercase tracking-wider">
                In Progress
              </span>
            </div>
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
              {tasks.filter((t) => t.status === "in_progress").length}
            </span>
          </div>

          <div className="space-y-3">
            {tasks.filter((t) => t.status === "in_progress").length === 0 ? (
              <div className="p-4 rounded-xl border border-white/[0.04] bg-[#070A12] text-center text-xs text-slate-500">
                No active tasks
              </div>
            ) : (
              tasks
                .filter((t) => t.status === "in_progress")
                .map((t) => (
                  <div
                    key={t.id}
                    className="p-4 rounded-xl border border-cyan-500/30 bg-[#070A12] space-y-3"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-300 border border-cyan-500/30">
                        {t.priority}
                      </span>
                      <span className="text-[11px] text-cyan-400 flex items-center gap-1 font-mono">
                        <Clock className="w-3 h-3 animate-spin" />
                        {t.estimated_duration_minutes}m
                      </span>
                    </div>

                    <h3 className="text-xs font-semibold text-white leading-relaxed">{t.title}</h3>

                    <div className="flex items-center justify-between pt-2 border-t border-white/[0.06] text-xs">
                      <button
                        onClick={() => handleUpdateStatus(t.id, "completed")}
                        className="text-emerald-400 hover:text-emerald-300 flex items-center gap-1 text-[11px] font-medium cursor-pointer"
                      >
                        <Check className="w-3.5 h-3.5" />
                        <span>Complete & Verify</span>
                      </button>
                      <button
                        onClick={() => handleUpdateStatus(t.id, "pending")}
                        className="text-slate-500 hover:text-slate-300 p-1 cursor-pointer"
                        title="Move to pending"
                      >
                        <RotateCcw className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                ))
            )}
          </div>
        </div>

        {/* Completed Column */}
        <div className="p-5 rounded-2xl border border-white/[0.08] bg-[#0C121E]/90 backdrop-blur-sm space-y-4">
          <div className="flex items-center justify-between border-b border-white/[0.08] pb-3">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
              <span className="font-bold text-xs text-emerald-300 uppercase tracking-wider">
                Completed
              </span>
            </div>
            <span className="text-xs font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
              {tasks.filter((t) => t.status === "completed").length}
            </span>
          </div>

          <div className="space-y-3">
            {tasks.filter((t) => t.status === "completed").length === 0 ? (
              <div className="p-4 rounded-xl border border-white/[0.04] bg-[#070A12] text-center text-xs text-slate-500">
                No completed tasks
              </div>
            ) : (
              tasks
                .filter((t) => t.status === "completed")
                .map((t) => (
                  <div
                    key={t.id}
                    className="p-4 rounded-xl border border-emerald-500/20 bg-[#070A12]/80 space-y-2 opacity-85"
                  >
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-300 border border-emerald-500/30">
                        {t.priority}
                      </span>
                      <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                    </div>
                    <h3 className="text-xs font-medium text-slate-300 line-through leading-relaxed">
                      {t.title}
                    </h3>
                  </div>
                ))
            )}
          </div>
        </div>
      </div>

      {/* New Task Modal */}
      {showCreateModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
          <div className="w-full max-w-md p-6 rounded-2xl border border-white/[0.08] bg-[#0C121E] shadow-2xl space-y-4">
            <h2 className="text-base font-bold text-white">Create Action Task</h2>
            <form onSubmit={handleCreateTask} className="space-y-4">
              <div className="space-y-1">
                <label className="text-xs text-slate-300">Task Title</label>
                <input
                  type="text"
                  required
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  placeholder="e.g., Audit Terraform configuration for VPC peering"
                  className="w-full bg-[#070A12] border border-white/10 rounded-xl px-3 py-2 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-400"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-1">
                  <label className="text-xs text-slate-300">Priority</label>
                  <select
                    value={newPriority}
                    onChange={(e) => setNewPriority(e.target.value)}
                    className="w-full bg-[#070A12] border border-white/10 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-cyan-400"
                  >
                    <option value="low">Low</option>
                    <option value="medium">Medium</option>
                    <option value="high">High</option>
                  </select>
                </div>

                <div className="space-y-1">
                  <label className="text-xs text-slate-300">Est. Minutes</label>
                  <input
                    type="number"
                    value={newDuration}
                    onChange={(e) => setNewDuration(e.target.value)}
                    className="w-full bg-[#070A12] border border-white/10 rounded-xl px-3 py-2 text-xs text-white focus:outline-none focus:border-cyan-400"
                  />
                </div>
              </div>

              <div className="flex items-center justify-end gap-2 pt-2 border-t border-white/[0.08]">
                <button
                  type="button"
                  onClick={() => setShowCreateModal(false)}
                  className="px-4 py-2 rounded-xl text-xs text-slate-400 hover:text-white"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 hover:from-cyan-400 hover:to-indigo-500 text-white font-semibold text-xs shadow-md shadow-cyan-500/20"
                >
                  Save Task
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
